---
# Install docker and docker-compose
- name: Install required system packages
  apt:
    state: latest
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
  tags:
    - docker

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Verify that we have the key with the fingerprint
  apt_key:
    id: "{{ apt_docker_key }}"
    state: present
  tags:
    - docker

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present
  tags:
    - docker

- name: Update apt and install docker-ce
  apt:
    state: latest
    update_cache: yes
    name: docker-ce
  tags:
    - docker

- name: Install Docker Module for Python
  pip:
    name: docker
  tags:
    - docker

- name: Add remote "{{ docker_user }}" user to "docker" group
  user:
    name: "{{ docker_user }}"
    group: "docker"
    append: yes
  tags:
    - docker

- name: Install docker-compose
  get_url: 
    url : "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
  tags:
    - docker
    - docker-compose
